version: "3.7"
services:
  backend_api:
    build:
      context: .
      dockerfile: ./backend-api-Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    networks:
      - backend
      - frontend
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./settings:/settings

  workers_api:
    build:
      context: .
      dockerfile: ./backend-workers-Dockerfile
    restart: always
    privileged: true
    depends_on:
      - redis
      - mongodb
    networks:
      - backend
      - frontend
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./settings:/settings
      - ${SRCVBFOLDER}:${DSTVBFOLDER}

  frontend_website:
    build:
      context: .
      dockerfile: ./frontend-Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - backend_api
    links:
      - backend_api
    networks:
      - backend
      - frontend

  redis:
    image: redis
    command: redis-server --requirepass changeme_927dhgs810d712fxs1
    networks:
      - backend
      - frontend
    ports:
     - "6379:6379"
    logging:
      driver: none

  mongodb:
    build:
      context: .
      dockerfile: ./mongodb-Dockerfile
    networks:
      - backend
      - frontend
    ports:
     - "27017:27017"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./folders/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme_498fjh29hd61fsaqyu
      MONGO_INITDB_ROOT_PASSWORD: changeme_0dk28de6g1s8ghwsqw
    command: mongod --auth
    logging:
      driver: none

networks:
  frontend:
    internal: false
  backend:
    internal: true